# Generated by Django 5.1.7 on 2025-03-19 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercice',
            old_name='fichier_pdf',
            new_name='fichier_sujet',
        ),
        migrations.RenameField(
            model_name='soumission',
            old_name='date',
            new_name='date_soumission',
        ),
        migrations.RenameField(
            model_name='soumission',
            old_name='fichier_pdf',
            new_name='fichier_soumis',
        ),
        migrations.AddField(
            model_name='exercice',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ModeleCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_correction', models.FileField(upload_to='corrections/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercice')),
            ],
        ),
    ]
